name: cache
on: { push: { branches: [osk-cpu-fix] }, workflow_dispatch: {} }
jobs:
  cache:
    uses: rivavolt/ci/.github/workflows/avolt-build-cache.yml@v1
    with: { attr: ".#default" }
    secrets: inherit
